# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nba_polymarket/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nba_polymarket/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enba_polymarket/v1/common.proto\x12\x11nba_polymarket.v1\"w\n\rEventMetadata\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\x12\x13\n\x0bingested_ns\x18\x02 \x01(\x03\x12)\n\x06source\x18\x03 \x01(\x0e\x32\x19.nba_polymarket.v1.Source\x12\x10\n\x08trace_id\x18\x04 \x01(\t*\xb8\x01\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x18\n\x14SOURCE_POLYMARKET_WS\x10\x01\x12\x1a\n\x16SOURCE_POLYMARKET_REST\x10\x02\x12\x12\n\x0eSOURCE_NBA_API\x10\x03\x12\x0f\n\x0bSOURCE_ESPN\x10\x04\x12\x1b\n\x17SOURCE_SIMULATOR_REPLAY\x10\x05\x12\x1e\n\x1aSOURCE_SIMULATOR_SYNTHETIC\x10\x06\x42&\n\x15\x63om.nba_polymarket.v1B\x0b\x43ommonProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nba_polymarket.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.nba_polymarket.v1B\013CommonProtoP\001'
  _globals['_SOURCE']._serialized_start=175
  _globals['_SOURCE']._serialized_end=359
  _globals['_EVENTMETADATA']._serialized_start=53
  _globals['_EVENTMETADATA']._serialized_end=172
# @@protoc_insertion_point(module_scope)
