# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nba_polymarket/v1/game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nba_polymarket/v1/game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nba_polymarket.v1 import common_pb2 as nba__polymarket_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cnba_polymarket/v1/game.proto\x12\x11nba_polymarket.v1\x1a\x1enba_polymarket/v1/common.proto\"\x87\x02\n\tGameEvent\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .nba_polymarket.v1.EventMetadata\x12\x0f\n\x07game_id\x18\x02 \x01(\t\x12\x11\n\thome_team\x18\x03 \x01(\t\x12\x11\n\taway_team\x18\x04 \x01(\t\x12\x12\n\nhome_score\x18\x05 \x01(\x05\x12\x12\n\naway_score\x18\x06 \x01(\x05\x12\x0e\n\x06period\x18\x07 \x01(\x05\x12\x15\n\rgame_clock_ms\x18\x08 \x01(\x05\x12+\n\x05phase\x18\t \x01(\x0e\x32\x1c.nba_polymarket.v1.GamePhase\x12\x17\n\x0fpossession_team\x18\n \x01(\t*\xa9\x01\n\tGamePhase\x12\x1a\n\x16GAME_PHASE_UNSPECIFIED\x10\x00\x12\x17\n\x13GAME_PHASE_PRE_GAME\x10\x01\x12\x1a\n\x16GAME_PHASE_IN_PROGRESS\x10\x02\x12\x17\n\x13GAME_PHASE_HALFTIME\x10\x03\x12\x1c\n\x18GAME_PHASE_QUARTER_BREAK\x10\x04\x12\x14\n\x10GAME_PHASE_FINAL\x10\x05\x42$\n\x15\x63om.nba_polymarket.v1B\tGameProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nba_polymarket.v1.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.nba_polymarket.v1B\tGameProtoP\001'
  _globals['_GAMEPHASE']._serialized_start=350
  _globals['_GAMEPHASE']._serialized_end=519
  _globals['_GAMEEVENT']._serialized_start=84
  _globals['_GAMEEVENT']._serialized_end=347
# @@protoc_insertion_point(module_scope)
