# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nba_polymarket/v1/order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nba_polymarket/v1/order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nba_polymarket.v1 import common_pb2 as nba__polymarket_dot_v1_dot_common__pb2
from nba_polymarket.v1 import market_pb2 as nba__polymarket_dot_v1_dot_market__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnba_polymarket/v1/order.proto\x12\x11nba_polymarket.v1\x1a\x1enba_polymarket/v1/common.proto\x1a\x1enba_polymarket/v1/market.proto\"\xa6\x02\n\x05Order\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .nba_polymarket.v1.EventMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63ondition_id\x18\x04 \x01(\t\x12\x10\n\x08token_id\x18\x05 \x01(\t\x12%\n\x04side\x18\x06 \x01(\x0e\x32\x17.nba_polymarket.v1.Side\x12*\n\x04type\x18\x07 \x01(\x0e\x32\x1c.nba_polymarket.v1.OrderType\x12\r\n\x05price\x18\x08 \x01(\x01\x12\x0c\n\x04size\x18\t \x01(\x01\x12.\n\x06status\x18\n \x01(\x0e\x32\x1e.nba_polymarket.v1.OrderStatus\"r\n\x04\x46ill\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .nba_polymarket.v1.EventMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0c\n\x04size\x18\x04 \x01(\x01\x12\x0b\n\x03\x66\x65\x65\x18\x05 \x01(\x01\"\x87\x01\n\x08Position\x12\x14\n\x0c\x63ondition_id\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\x17\n\x0f\x61vg_entry_price\x18\x04 \x01(\x01\x12\x16\n\x0eunrealized_pnl\x18\x05 \x01(\x01\x12\x14\n\x0crealized_pnl\x18\x06 \x01(\x01*c\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eORDER_TYPE_GTC\x10\x01\x12\x12\n\x0eORDER_TYPE_FOK\x10\x02\x12\x12\n\x0eORDER_TYPE_IOC\x10\x03*\xce\x01\n\x0bOrderStatus\x12\x1c\n\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n\x11ORDER_STATUS_OPEN\x10\x02\x12!\n\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x03\x12\x17\n\x13ORDER_STATUS_FILLED\x10\x04\x12\x19\n\x15ORDER_STATUS_CANCELED\x10\x05\x12\x19\n\x15ORDER_STATUS_REJECTED\x10\x06\x42%\n\x15\x63om.nba_polymarket.v1B\nOrderProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nba_polymarket.v1.order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.nba_polymarket.v1B\nOrderProtoP\001'
  _globals['_ORDERTYPE']._serialized_start=667
  _globals['_ORDERTYPE']._serialized_end=766
  _globals['_ORDERSTATUS']._serialized_start=769
  _globals['_ORDERSTATUS']._serialized_end=975
  _globals['_ORDER']._serialized_start=117
  _globals['_ORDER']._serialized_end=411
  _globals['_FILL']._serialized_start=413
  _globals['_FILL']._serialized_end=527
  _globals['_POSITION']._serialized_start=530
  _globals['_POSITION']._serialized_end=665
# @@protoc_insertion_point(module_scope)
