# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nba_polymarket/v1/signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nba_polymarket/v1/signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nba_polymarket.v1 import common_pb2 as nba__polymarket_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enba_polymarket/v1/signal.proto\x12\x11nba_polymarket.v1\x1a\x1enba_polymarket/v1/common.proto\"\xee\x01\n\x06Signal\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .nba_polymarket.v1.EventMetadata\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ondition_id\x18\x03 \x01(\t\x12\x10\n\x08token_id\x18\x04 \x01(\t\x12/\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x1f.nba_polymarket.v1.SignalAction\x12\x14\n\x0ctarget_price\x18\x06 \x01(\x01\x12\x0c\n\x04size\x18\x07 \x01(\x01\x12\x12\n\nconfidence\x18\x08 \x01(\x01\x12\x0e\n\x06reason\x18\t \x01(\t*\x8d\x01\n\x0cSignalAction\x12\x1d\n\x19SIGNAL_ACTION_UNSPECIFIED\x10\x00\x12\x15\n\x11SIGNAL_ACTION_BUY\x10\x01\x12\x16\n\x12SIGNAL_ACTION_SELL\x10\x02\x12\x17\n\x13SIGNAL_ACTION_CLOSE\x10\x03\x12\x16\n\x12SIGNAL_ACTION_HOLD\x10\x04\x42&\n\x15\x63om.nba_polymarket.v1B\x0bSignalProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nba_polymarket.v1.signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.nba_polymarket.v1B\013SignalProtoP\001'
  _globals['_SIGNALACTION']._serialized_start=327
  _globals['_SIGNALACTION']._serialized_end=468
  _globals['_SIGNAL']._serialized_start=86
  _globals['_SIGNAL']._serialized_end=324
# @@protoc_insertion_point(module_scope)
